from typing import Protocol
from uuid import UUID

from app.modules.identity.domain.entities import Membership, Organization, User


class UserRepository(Protocol):
    def get_by_id(self, user_id: UUID) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def create(self, user: User) -> User: ...

    def update(self, user: User) -> User: ...

    def soft_delete(self, user_id: UUID) -> None: ...


class OrganizationRepository(Protocol):
    def get_by_id(self, organization_id: UUID) -> Organization | None: ...

    def get_by_slug(self, slug: str) -> Organization | None: ...

    def create(self, organization: Organization) -> Organization: ...

    def update(self, organization: Organization) -> Organization: ...

    def soft_delete(self, organization_id: UUID) -> None: ...


class MembershipRepository(Protocol):
    def get_by_id(self, membership_id: UUID) -> Membership | None: ...

    def get_by_user_and_organization(
        self,
        user_id: UUID,
        organization_id: UUID,
    ) -> Membership | None: ...

    def list_by_user_id(self, user_id: UUID) -> list[Membership]: ...

    def list_by_organization_id(self, organization_id: UUID) -> list[Membership]: ...

    def create(self, membership: Membership) -> Membership: ...

    def update(self, membership: Membership) -> Membership: ...

    def soft_delete(self, membership_id: UUID) -> None: ...
